rmcs_flight_controller:
  ros__parameters:
    debug: false
    pid:
      outer:
        kp: 0.07
        ki: 0.0
        kd: 0.01
      inner:
        kp: 180.0
        ki: 0.0
        kd: 0.2
        
    control_frequency: 20
    mid360_data_topic: "/rmcs_slam/position"
    dji:
      config_path: "/workspaces/workspace/rmcs_flight/rmcs_flight/src/bringup/config/Dji_config.txt"