rmcs_flight_controller:
  ros__parameters:
    debug: false
    pid:
      outer:
        kp: 20.0
        ki: 0.0
        kd: 0.0
      inner:
        kp: 20.0
        ki: 0.0
        kd: 0.5
    serial:
      port: "/dev/ttyUSB0"
      baudrate: 115200
    control_frequency: 10
    mid360_data_topic: "/rmcs_slam/position"
    dji:
      config_path: "/workspaces/workspace/rmcs_flight/rmcs_flight/src/bringup/config/Dji_config.txt"